#!/usr/bin/env python3
"""Builds mosques.js: the featured mosques' year timetables for the live preview.

The page can't call mawaqit.net itself (no CORS), so the timetables are baked
in. Each mosque page embeds a `confData` object with the full year calendar;
this reads the same thing the app reads (see MawaqitClient.swift) and writes
it out compactly. Re-run once a year, or whenever a mosque changes its times:

    python3 scripts/build-mosques.py
"""

import json
import re
import urllib.request
from datetime import date
from pathlib import Path

# id -> (mawaqit slug, display name, city). Names are tidied by hand: mawaqit
# stores some in capitals or with the city appended.
MOSQUES = {
    "paris": ("grande-mosquee-de-paris", "Grande Mosquée de Paris", "Paris"),
    "lyon": ("grande-mosquee-de-lyon-lyon-69008-france", "Grande Mosquée de Lyon", "Lyon"),
    "marseille": ("mosquee-de-frais-vallon-marseille-13013-france-1", "Mosquée de Frais Vallon", "Marseille"),
    "brussels": ("gmb", "La Grande Mosquée de Bruxelles", "Bruxelles"),
    "london": ("hedon-mosque-islamic-london-united-kingdom", "Hendon Mosque & Islamic Centre", "London"),
    "montreal": ("alsalam-mtl", "مسجد السلام", "Montréal"),
}

CONF_DATA = re.compile(r"(?:var|let)\s+confData\s*=\s*(\{[\s\S]*?\})\s*;")
HHMM = re.compile(r"^\d{2}:\d{2}$")


def fetch_conf(slug):
    request = urllib.request.Request(
        f"https://mawaqit.net/fr/{slug}", headers={"User-Agent": "Mozilla/5.0"}
    )
    html = urllib.request.urlopen(request, timeout=30).read().decode("utf-8")
    match = CONF_DATA.search(html)
    if not match:
        raise SystemExit(f"{slug}: no confData on the page")
    return json.loads(match.group(1))


def pack_month(month, label):
    """One string per month: each day is 24 digits, [fajr, sunrise, dhuhr,
    asr, maghrib, isha] as HHMM, days in order from the 1st."""
    days = sorted(month, key=int)
    if [int(d) for d in days] != list(range(1, len(days) + 1)):
        raise SystemExit(f"{label}: gap in the days of a month")
    out = []
    for day in days:
        times = month[day]
        if len(times) != 6 or not all(HHMM.match(t) for t in times):
            raise SystemExit(f"{label}: unexpected day {day}: {times}")
        out.append("".join(t.replace(":", "") for t in times))
    return "".join(out)


def main():
    result = {}
    for key, (slug, name, city) in MOSQUES.items():
        conf = fetch_conf(slug)
        calendar = conf["calendar"]
        if len(calendar) != 12:
            raise SystemExit(f"{slug}: expected 12 months, got {len(calendar)}")
        result[key] = {
            "name": name,
            "city": city,
            "tz": conf["timezone"],
            "jumua": [t for t in (conf.get("jumua"), conf.get("jumua2"), conf.get("jumua3")) if t],
            "cal": [pack_month(m, f"{slug} month {i + 1}") for i, m in enumerate(calendar)],
        }
        print(f"{key:10} {conf['timezone']:16} jumua={result[key]['jumua']}")

    target = Path(__file__).resolve().parent.parent / "mosques.js"
    body = json.dumps(result, ensure_ascii=False, separators=(",", ":"))
    target.write_text(
        f"/* Featured mosques' timetables, from public mawaqit.net pages on {date.today()}.\n"
        f"   Generated by scripts/build-mosques.py. Don't edit by hand. */\n"
        f"window.NP_MOSQUES = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {target} ({target.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
